DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(
    ID BIGSERIAL NOT NULL PRIMARY KEY AUTO_INCREMENT,
    FIO VARCHAR(255) NOT NULL,
    DATE_OF_BIRCH DATE NOT NULL,
    DATE_OF_DEATH DATE
);

DROP TABLE IF EXISTS GENRES;
 CREATE TABLE GENRES(
     ID BIGSERIAL NOT NULL PRIMARY KEY AUTO_INCREMENT,
     NAME VARCHAR(255) NOT NULL);

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(
     ID BIGSERIAL NOT NULL PRIMARY KEY AUTO_INCREMENT,
     NAME VARCHAR(255) NOT NULL,
     ISBN VARCHAR(255),
     AUTHOR_ID BIGINT NOT NULL,
     GENRE_ID BIGINT NOT NULL,
     foreign key (AUTHOR_ID) references AUTHORS,
     foreign key (GENRE_ID) references GENRES);
CREATE SEQUENCE BOOKS_SEQ;

